sudo: required
services:
    - docker

before_install:
    -docker build -t kris/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run kris/react-test npm test -- --coverage

after_succes:
    - docker build -t kris/multi-client ./client
    - docker build -t kris/multi-nginx ./nginx
    - docker build -t kris/multi-server ./server
    - docker build -t kris/multi-worker ./worker
    # Login in to docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
    - docker push kris/multi-client
    - docker push kris/multi-nginx
    - docker push kris/multi-server
    - docker push kris/multi-worker